analytics_data_stack:
  outputs:
    dev:
      dbname: webshop
      host: localhost
      pass: admin
      port: 5432
      schema: "{{ env_var('DBT_DEV_SCHEMA', 'dev') }}"
      threads: 4
      type: postgres
      user: admin
    test:
      dbname: webshop
      host: test_postgres
      pass: admin
      port: 5432
      schema: "ci_test_{{ env_var('GIT_SHA', 'test') }}"
      threads: 4
      type: postgres
      user: admin
    prod:
      dbname: webshop
      host: localhost
      pass: admin
      port: 2345
      schema: not_used
      threads: 4
      type: postgres
      user: admin
    sample-dev:
      dbname: webshop
      host: localhost
      pass: admin
      port: 5432
      schema: raw
      threads: 4
      type: postgres
      user: admin
    sample-test:
      dbname: webshop
      host: test_postgres
      pass: admin
      port: 5432
      schema: raw
      threads: 4
      type: postgres
      user: admin
  target: dev
