name: CI_pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  CI_jobs:
    runs-on: self-hosted
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB}}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: Checkout # clones and pulls the repo at pull request SHA
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python
        run: uv python install

      - name: Install deps
        run: uv sync

      - name: Install Project Dependencies
        run: uv sync --group ci

      - name: Ruff Linting
        uses: astral-sh/ruff-action@v3

      - name: dbt build
        run: |
            cd ./dbt/analytics_data_stack/
            uv run dbt debug --target test
            uv run dbt deps
            uv run dbt build --target test

      - name: Save dbt manifest.json
        uses: actions/upload-artifact@v4
        with:
          name: manifest.json
          path: dbt/analytics_data_stack/target/manifest.json
          overwrite: True

      - name: Download dbt manifest.json
        uses: actions/download-artifact@v4
        with:
          name: manifest.json
          path: /runner/data/artifatcs/
